### ISSUE TITLE
Support: toText() method 

### ISSUE THREAD

**Issue by dooven** [JonasWanke/rrule#5]
Hi Jonas, thanks for this awesome library. 

Just wondering if you're planning to add the `toText()` method that generates a textual representation of a rule 

https://github.com/jakubroztocil/rrule#rruleprototypetotextgettext-language

**Comment by JonasWanke** [comment]
Yes, conversion to a textual representation (and probably from as well) will be added eventually, though I don't know when I'll have the time to implement it. I hope that I can start working on it next week or the week after.

**Comment by JonasWanke** [comment]
Brief update: I'm working on it and have already made some progress. Recurrence rules with a frequency of daily, weekly, monthly and yearly are already supported, with the exception of `byHours`, `byMinutes`, `bySeconds` & `bySetPositions`. Other frequencies (hourly, minutely & secondly) still have to be done. Also, there's only support for English at the moment, but adding support for German should be relatively easy. I'm not that fluent in other languages, so I'll need help if more should be supported.

Some examples that already work:
- `RRULE:FREQ=WEEKLY;BYMONTH=1,2,3,8,9;BYDAY=MO,WE,TH,FR,SU`: 'Weekly in January – March, August & September on Monday, Wednesday – Friday & Sunday'
- `RRULE:FREQ=WEEKLY;INTERVAL=2;BYMONTH=1,2,3;BYDAY=MO,TU,WE,TH,FR,SU`: Every other week in January – March on weekdays & Sunday
- `RRULE:FREQ=MONTHLY;BYDAY=MO,TU,WE,1TH,1FR,2TH,2FR,2SA,-2TH,-2FR,-2SU,-1TH,-1FR,-1SU;BYMONTHDAY=1,2,3,4,5,26,-3,-2,-1`: Monthly on every Monday – Wednesday, the 1st Thursday & Friday, the 2nd Thursday – Saturday, the 2nd-to-last Thursday, Friday & Sunday, and the last Thursday, Friday & Sunday that are also the 1st – 5th, 26th, or 3rd-to-last – last day of the month
- `RRULE:FREQ=YEARLY;BYYEARDAY=1,-1`: Annually on the 1st & last day of the year
- `RRULE:FREQ=YEARLY;BYMONTH=1,12;BYWEEKNO=1,-1;BYYEARDAY=1,-1;BYMONTHDAY=1,-1;BYDAY=MO,WE`: Annually on every Monday & Wednesday that are also the 1st or last day of the month, that are also the 1st or last day of the year, that are also in the 1st or last week of the year, and that are also in January or December

You can already use this feature by depending directly on the `issue/5-support-totext-method`-branch, though the API might still change slightly.

@dooven Do you need support for `bySetPositions` or frequencies hourly, minutely or secondly? Otherwise, I'll finish the conversion of already supported frequencies (support `byHours`, `byMinutes` & `bySeconds)` and support German, and then release that. Support for the rest would be done later on.

**Comment by dooven** [comment]
Hi @JonasWanke, appreciate the awesome work you have done. Unfortunately, i am unable to assist you with the  translation since I don't know German as well. 

> Do you need support for bySetPositions or frequencies hourly, minutely or secondly?

Yeah I need support for `bySetPositions` :)

**Comment by JonasWanke** [comment]
This has finally been released in [v0.1.1](https://github.com/JonasWanke/rrule/releases/tag/v0.1.1) 🎉

Feel free to open new issues for supporting more attributes/frequencies or languages, or for better wording of supported recurrence rules. (See #7 for what is currently supported.)

**Comment by dooven** [comment]
Thanks @JonasWanke !!
